# Generated by Django 2.1.5 on 2019-03-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
    ]
